[package]
name = "kicad-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
sexp = "1.1.4"
opencascade = { version = "0.1", path = "../opencascade" }
glam = { version = "0.23", features = ["bytemuck"] }
