on: [push]

name: Clang Format

jobs:
  fmt:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '14'
          check-path: crates/opencascade-sys/include
