on:
  push:
    branches:
      - main
  pull_request:

name: Cargo Clippy

jobs:
  clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings
